### ISSUE TITLE
Move presence only stuff into something towards end

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB-teaching#11]
Maybe shorter?

**Comment by ericward-noaa** [comment]
@seananderson @ecophilina -- I'm thinking about this, and am not sure what we decided on about the initial tree example in 03-tree-example.Rmd. The right way to model presence-only data is in 06-presence-only.Rmd. What I'm thinking is combining these into a single set of slides, condensing material, and moving toward the end of the deck. Then deleting the two original sets. Thoughts??

**Comment by ecophilina** [comment]
Sounds good to me.

**Comment by seananderson** [comment]
Sounds good

**Comment by ericward-noaa** [comment]
Ok, fixed here: https://github.com/pbs-assess/sdmTMB-teaching/commit/b3b4a2da59812d9652925530e6326f084f9b1ad6

* Rest of Rmds need to probably be re-numbered, along with the new pcod ones
