### ISSUE TITLE
workflow chart clarification question

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [pbs-assess/sdmTMB-teaching#2]
Hey Folks, carving out a bit of time this week to work on NSAW materials.  Just to check that I am remembering/noted things correctly, did we 1) want a flowchart of basic sdmTMB steps in an analysis (this is what I thought the idea was), or 2) a flowchart representing our bulleted agenda for the workshop?

**Comment by seananderson** [comment]
Option 1

**Comment by Lewis-Barnett-NOAA** [comment]
roger that, thanks
