### ISSUE TITLE
Add a few slides in a new set on families

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB-teaching#6]
Tweedie, delta-models, truncated models

**Comment by ericward-noaa** [comment]
Addressed here:
https://github.com/pbs-assess/sdmTMB-teaching/commit/351aa2b46ded107c024f2a4552a74870ba078c73

**Comment by seananderson** [comment]
Can we add a bit on the delta models and the things you need to know about working with them (by default everything shared, some things can be split as lists).

**Comment by ericward-noaa** [comment]
yep -- done
